std_msgs/Header header 
#  [] [0|1]
bool acc_en_status 
#  [] [0|7]
int32 acc_control_board_status 
#  [] [0|15]
int32 acc_control_status 
#  [] [0|1]
bool acc_user_can_err 
#  [] [0|1]
bool acc_err 
#  [km/h] [0|255]
int32 vs 
#  [m/s^2] [-10.23|10.24]
float32 long_accel 
#  [] [0|1]
bool hazard_en 
#  [] [0|1]
bool turn_left_en 
#  [] [0|1]
bool turn_right_en 
#  [] [0|1]
bool acc_veh_err 
#  [] [0|15]
int32 g_sel_disp 
#  [] [0|255]
int32 acc_alive_cnt 
