std_msgs/Header header 
#  [] [0|1]
bool eps_en_status 
#  [] [0|2]
int32 eps_control_board_status 
#  [] [0|15]
int32 eps_control_status 
#  [] [0|1]
bool eps_user_can_err 
#  [] [0|1]
bool eps_err 
#  [] [0|1]
bool eps_veh_can_err 
#  [] [0|1]
bool eps_sas_err 
#  [] [0|1]
bool override_ignore_status 
#  [] [0|1]
bool override_status 
#  [] [-500|500]
float32 str_ang 
#  [] [-20.48|20.47]
float32 str_drv_tq 
#  [] [-204.8|204.7]
float32 str_out_tq 
#  [] [0|255]
int32 eps_alive_cnt 
